'use strict';

const runtimeIssueLog=[];
const activeOperations=new Map();
function diagnosticLog(level,area,message,error=null,context={}){
  const item={level,area,message:String(message||error?.message||'Evento'),detail:error?String(error.stack||error.message||error):'',context,at:new Date().toISOString()};
  runtimeIssueLog.push(item);if(runtimeIssueLog.length>100)runtimeIssueLog.shift();
  (level==='error'?console.error:level==='warn'?console.warn:console.info)(`[CdB:${area}] ${item.message}`,error||'');return item;
}
function rememberRuntimeIssue(kind,value){return diagnosticLog('error',kind,value?.message||value?.reason?.message||value?.reason||value||'Errore sconosciuto',value?.error||value?.reason||value);}
window.addEventListener('error',event=>rememberRuntimeIssue('javascript',event.error||event.message));
window.addEventListener('unhandledrejection',event=>{rememberRuntimeIssue('promise',event.reason);event.preventDefault();});
function debounce(fn,wait=180){let timer;return function(...args){clearTimeout(timer);timer=setTimeout(()=>fn.apply(this,args),wait);};}
function throttle(fn,wait=80){let last=0,timer,pending;return function(...args){pending=args;const run=()=>{last=Date.now();timer=null;fn.apply(this,pending);};const delay=wait-(Date.now()-last);if(delay<=0)run();else if(!timer)timer=setTimeout(run,delay);};}
function nextFrame(){return new Promise(resolve=>requestAnimationFrame(()=>resolve()));}
function withTimeout(task,ms=15000,label='Operazione',controller=null){let timer,abortHandler;const promise=typeof task==='function'?task(controller?.signal):task,timeoutPromise=new Promise((_,reject)=>{timer=setTimeout(()=>{const error=new Error(`${label}: tempo scaduto. Riprova o riduci il numero/dimensione delle immagini.`);error.name='TimeoutError';controller?.abort(error);reject(error);},ms);}),abortPromise=controller?new Promise((_,reject)=>{abortHandler=()=>{const error=controller.signal.reason instanceof Error?controller.signal.reason:new DOMException('Operazione annullata','AbortError');reject(error);};if(controller.signal.aborted)abortHandler();else controller.signal.addEventListener('abort',abortHandler,{once:true});}):new Promise(()=>{});return Promise.race([promise,timeoutPromise,abortPromise]).finally(()=>{clearTimeout(timer);if(abortHandler)controller?.signal.removeEventListener('abort',abortHandler);});}
async function runExclusive(key,{buttons=[],label='Operazione',timeout=120000}={},task){if(activeOperations.has(key))return activeOperations.get(key);const controller=new AbortController();buttons.filter(Boolean).forEach(button=>button.disabled=true);const promise=(async()=>{try{return await withTimeout(task,timeout,label,controller);}catch(error){diagnosticLog(error?.name==='AbortError'?'warn':'error',key,error?.message||label,error);throw error;}finally{buttons.filter(Boolean).forEach(button=>button.disabled=false);activeOperations.delete(key);}})();promise.controller=controller;activeOperations.set(key,promise);return promise;}
function cancelOperation(key){const operation=activeOperations.get(key);if(!operation?.controller)return false;operation.controller.abort();return true;}
function userError(error,fallback='Operazione non riuscita'){const message=error?.name==='AbortError'?'Operazione annullata.':error?.message||fallback;showToast?.(message);return message;}
function safeAsync(area,action,{fallback='Operazione non riuscita'}={}){return Promise.resolve().then(action).catch(error=>{diagnosticLog('error',area,error?.message||fallback,error);userError(error,fallback);});}
function loadExternalScript(src,globalName,{timeout=15000}={}){return withTimeout(new Promise((resolve,reject)=>{if(globalName&&window[globalName])return resolve(window[globalName]);const existing=document.querySelector(`script[data-cdb-src="${src}"]`);if(existing){existing.addEventListener('load',()=>resolve(globalName?window[globalName]:true),{once:true});existing.addEventListener('error',()=>reject(new Error(`Impossibile caricare ${globalName||'la dipendenza'}. Controlla la connessione.`)),{once:true});return;}const script=document.createElement('script');script.src=src;script.async=true;script.dataset.cdbSrc=src;script.onload=()=>resolve(globalName?window[globalName]:true);script.onerror=()=>reject(new Error(`Impossibile caricare ${globalName||'la dipendenza'}. Controlla la connessione.`));document.head.appendChild(script);}),timeout,`Caricamento ${globalName||'dipendenza'}`);}
