'use strict';

function qualityIssue(severity,slideIndex,key,title,message){return{id:uid(),severity,slideIndex,key,title,message};}
let affinityFontDataUrlPromise=null;
let affinityLogoMarkupPromise=null;
async function loadAffinityFontDataUrl(){
  if(!affinityFontDataUrlPromise)affinityFontDataUrlPromise=(async()=>{const response=await withTimeout(fetch('assets/fonts/NickelGothicV3-Regular.otf',{cache:'force-cache'}),10000,'Font Nickel Gothic');if(!response.ok)throw new Error(`Font Nickel Gothic non disponibile (${response.status})`);return blobToDataUrl(await response.blob());})().catch(error=>{affinityFontDataUrlPromise=null;diagnosticLog('warn','affinity-font','Font non incorporato nello SVG',error);return'';});
  return affinityFontDataUrlPromise;
}
async function loadAffinityLogoMarkup(){
  if(!affinityLogoMarkupPromise)affinityLogoMarkupPromise=(async()=>{const response=await withTimeout(fetch('assets/logo.svg',{cache:'force-cache'}),10000,'Logo vettoriale');if(!response.ok)throw new Error(`Logo vettoriale non disponibile (${response.status})`);const source=await response.text(),match=source.match(/<svg\b[^>]*>([\s\S]*?)<\/svg>/i);if(!match)throw new Error('Logo SVG non valido');return match[1].replace(/<title>[\s\S]*?<\/title>/i,'');})().catch(error=>{affinityLogoMarkupPromise=null;diagnosticLog('warn','affinity-logo','Logo vettoriale non incorporato nello SVG',error);return'';});
  return affinityLogoMarkupPromise;
}
async function ensureExportFonts(){await Promise.all([{name:'Nickel Gothic v3',weight:400},{name:'Anton',weight:400},{name:'Anybody',weight:800},{name:'Archivo',weight:800},{name:'Saira',weight:800}].map(f=>document.fonts?.load(`${f.weight} 90px "${f.name}"`).catch(()=>null))||[]);}
function transformedBoxBounds(box,state,cx,cy,baseRotation=0){if(!box)return null;return transformedRectBounds({x:box.x,y:box.y,w:box.w,h:box.h,cx,cy},state,baseRotation);}
function textQualityMetrics(slide,key){const style=elementData(slide,key),layout=layoutForElement(slide,key);if(!style||!layout)return null;const lines=wrapLines(style.text,style,layout.maxWidth||style.maxWidth||820),factor=(style.width||100)/100;measureCtx.font=`${style.weight||400} ${style.size||60}px "${normalizeFontName(style.font)||'Anton'}"`;const widths=lines.map(line=>measureCtx.measureText(line||' ').width*factor),width=Math.max(4,...widths),height=Math.max(style.size,((lines.length-1)*style.size*style.lineHeight)+style.size*1.08);let x=layout.x;if(layout.align==='center')x-=width/2;else if(layout.align==='right')x-=width;const y=layout.y-style.size*.84;const bounds=transformedBoxBounds({x,y,w:width,h:height},style,layout.cx,layout.cy,0);return{lines,width,height,bounds,layout,style};}
function qualityBoundsForElement(slide,key){const type=elementType(key),data=elementData(slide,key),layout=layoutForElement(slide,key);if(type==='text')return textQualityMetrics(slide,key)?.bounds||null;if(['image','logo','number','shape'].includes(type)){const base=key==='image'?(layout?.rotation||0):0;return transformedRectBounds(layout,data||{},base);}return null;}
function imagePixelDensity(state,layout){if(!state?.src||!layout?.w||!layout?.h)return null;const crop=normalizeCrop(state.crop||{});if(!crop.naturalW||!crop.naturalH)return null;const p=cropPlacement(state,layout),outer=Math.max(.05,Number(state.scale||1));return Math.min(crop.naturalW/Math.max(1,p.w*outer),crop.naturalH/Math.max(1,p.h*outer));}
function boundsOutsideCanvas(b,tolerance=12){return b&&(b.x<-tolerance||b.y<-tolerance||b.x+b.w>W+tolerance||b.y+b.h>H+tolerance);}
function boundsNearSafeEdge(b){return b&&(b.x<QUALITY_SAFE_MARGIN||b.y<QUALITY_SAFE_MARGIN||b.x+b.w>W-QUALITY_SAFE_MARGIN||b.y+b.h>H-QUALITY_SAFE_MARGIN);}
function boundsIntersection(a,b){if(!a||!b)return null;const x=Math.max(a.x,b.x),y=Math.max(a.y,b.y),right=Math.min(a.x+a.w,b.x+b.w),bottom=Math.min(a.y+a.h,b.y+b.h);if(right<=x||bottom<=y)return null;return{x,y,w:right-x,h:bottom-y,area:(right-x)*(bottom-y)};}
function logoTextOverlap(slide,key,logoBounds=qualityBoundsForElement(slide,'logo')){const textBounds=qualityBoundsForElement(slide,key),intersection=boundsIntersection(logoBounds,textBounds);if(!intersection||!textBounds?.w||!textBounds?.h)return null;return{intersection,textBounds,ratio:intersection.area/(textBounds.w*textBounds.h)};}
function qualityFontLoaded(style){try{return document.fonts?.check(`${style.weight||400} 48px "${normalizeFontName(style.font)||'Anton'}"`)!==false;}catch(_){return true;}}
async function analyzeSlideQuality(slide,slideIndex){
  ensureLayerModel(slide);await hydrateImageMeta(slide.image);for(const ov of slide.overlays||[])await hydrateImageMeta(ov);const issues=[],slideNo=slideIndex+1;
  for(const key of ['title','subtitle',...(slide.freeTexts||[]).map(x=>`free:${x.id}`)]){
    const style=elementData(slide,key);if(!style)continue;const label=layerLabel(slide,key),text=String(style.text||'').trim(),state=layerState(slide,key);
    if(key==='title'&&!text)issues.push(qualityIssue('error',slideIndex,key,'Titolo mancante',`La slide ${slideNo} non ha un titolo.`));
    if(text&&state.visible===false)issues.push(qualityIssue('warning',slideIndex,key,`${label} nascosto`,`Il contenuto esiste ma il livello non è visibile.`));
    if(text&&layerOpacity(slide,key)<.35)issues.push(qualityIssue('warning',slideIndex,key,`${label} quasi trasparente`,`Opacità ${Math.round(layerOpacity(slide,key)*100)}%: potrebbe risultare illeggibile.`));
    if(text&&!qualityFontLoaded(style))issues.push(qualityIssue('warning',slideIndex,key,'Font non caricato',`${normalizeFontName(style.font)} non risulta disponibile nel browser.`));
    if(!text)continue;const metrics=textQualityMetrics(slide,key),b=metrics?.bounds;if(boundsOutsideCanvas(b))issues.push(qualityIssue('error',slideIndex,key,`${label} fuori dalla slide`,'Una parte del testo supera i bordi del formato 1080×1350.'));
    else if(boundsNearSafeEdge(b))issues.push(qualityIssue('warning',slideIndex,key,`${label} vicino al margine`,'Controlla che il testo non risulti troppo vicino al bordo su Instagram.'));
    const role=key==='title'?'title':key==='subtitle'?'subtitle':'free',limit=role==='free'?520:(QUALITY_TEXT_LIMITS[designOf(slide)]?.[role]||320),visualHeight=(metrics?.height||0)*(style.scale||1);
    if(visualHeight>limit*1.08)issues.push(qualityIssue('error',slideIndex,key,`${label} troppo lungo`,`Occupa circa ${Math.round(visualHeight)} px rispetto ai ${limit} px consigliati. Usa “Adatta testo” o riduci il contenuto.`));
    else if(visualHeight>limit*.92)issues.push(qualityIssue('warning',slideIndex,key,`${label} molto pieno`,'Il testo è vicino al limite previsto dal template.'));
    const visualSize=(style.size||0)*(style.scale||1);if((key==='title'&&visualSize<36)||(key!=='title'&&visualSize<24))issues.push(qualityIssue('warning',slideIndex,key,`${label} molto piccolo`,`Dimensione visiva circa ${Math.round(visualSize)} px.`));
  }
  const imageLayout=layoutForElement(slide,'image');if(imageLayout?.w>50&&imageLayout?.h>50&&layerVisible(slide,'image')){
    if(!slide.image?.src)issues.push(qualityIssue('warning',slideIndex,'image','Immagine principale assente','Il template prevede una fotografia, ma la slide è ancora vuota.'));
    else{const density=imagePixelDensity(slide.image,imageLayout);if(density!==null&&density<.48)issues.push(qualityIssue('error',slideIndex,'image','Immagine poco definita',`Densità stimata ${density.toFixed(2)}×: il PNG può apparire sgranato.`));else if(density!==null&&density<.78)issues.push(qualityIssue('warning',slideIndex,'image','Risoluzione immagine limitata',`Densità stimata ${density.toFixed(2)}× dopo il ritaglio.`));const provider=String(slide.imageProvider||'').toLowerCase();if(!slide.imageSource)issues.push(qualityIssue('info',slideIndex,'image','Fonte immagine non registrata','Conserva il link o il file originale prima della pubblicazione.'));else if(provider==='tmdb')issues.push(qualityIssue('warning',slideIndex,'image','Diritti immagine da verificare','TMDb cataloga il materiale ma non concede automaticamente il diritto di ripubblicarlo.'));else if(provider.includes('wikimedia')&&!/public domain|pubblico dominio|cc0|cc by/i.test(slide.imageLicense||''))issues.push(qualityIssue('warning',slideIndex,'image','Licenza Commons da verificare',slide.imageLicense||'Apri la fonte e controlla licenza e attribuzione.'));}
  }
  for(const ov of slide.overlays||[]){const key=`overlay:${ov.id}`,layout=layoutForElement(slide,key),b=qualityBoundsForElement(slide,key),density=imagePixelDensity(ov,layout);if(boundsOutsideCanvas(b))issues.push(qualityIssue('warning',slideIndex,key,'Foto libera oltre i bordi','Una parte della foto sovrapposta è fuori dalla slide.'));if(density!==null&&density<.55)issues.push(qualityIssue('warning',slideIndex,key,'Foto libera poco definita',`Densità stimata ${density.toFixed(2)}×.`));}
  const logoBounds=qualityBoundsForElement(slide,'logo');if(!layerVisible(slide,'logo')||layerOpacity(slide,'logo')<.15)issues.push(qualityIssue('warning',slideIndex,'logo','Logo non visibile','Il logo CdB è nascosto o quasi trasparente.'));else if(boundsOutsideCanvas(logoBounds))issues.push(qualityIssue('error',slideIndex,'logo','Logo fuori dalla slide','Riporta il logo dentro i bordi.'));
  if(layerVisible(slide,'logo')&&layerOpacity(slide,'logo')>=.15){
    for(const key of ['title','subtitle',...(slide.freeTexts||[]).map(x=>`free:${x.id}`)]){
      const style=elementData(slide,key),text=String(style?.text||'').trim();if(!text||!layerVisible(slide,key)||layerOpacity(slide,key)<.15)continue;
      const overlap=logoTextOverlap(slide,key,logoBounds);if(!overlap)continue;const percent=Math.round(overlap.ratio*100),label=layerLabel(slide,key);
      if(overlap.ratio>.05||overlap.intersection.h>Math.max(12,(style.size||40)*.28))issues.push(qualityIssue('error',slideIndex,key,'Logo sopra il testo',`Il logo copre circa il ${Math.max(1,percent)}% di ${label.toLowerCase()}. Sposta o riduci il logo, oppure riposiziona il testo prima di esportare.`));
      else issues.push(qualityIssue('warning',slideIndex,key,'Logo molto vicino al testo',`Logo e ${label.toLowerCase()} si sovrappongono leggermente (${Math.max(1,percent)}%). Verifica che ogni parola resti leggibile.`));
    }
  }
  return issues;
}
function projectQualityIssues(){const issues=[],imageMap=new Map();project.slides.forEach((slide,index)=>{if(slide.image?.src){const key=slideAssetKey(slide);const prev=imageMap.get(key)||[];prev.push(index);imageMap.set(key,prev);}});for(const indexes of imageMap.values())if(indexes.length>1)for(const index of indexes.slice(1))issues.push(qualityIssue('info',index,'image','Immagine ripetuta',`La stessa immagine compare anche nella slide ${indexes[0]+1}.`));const titleFonts=new Set(project.slides.map(s=>normalizeFontName(s.title?.font)).filter(Boolean));if(titleFonts.size>1)issues.push(qualityIssue('info',0,'title','Font dei titoli non uniforme',`Sono usati ${[...titleFonts].join(', ')}. Può essere voluto, ma controlla la coerenza.`));if(!project.name||project.name==='Nuovo carosello')issues.push(qualityIssue('info',0,'title','Nome progetto generico','Dai un nome riconoscibile al progetto prima del backup.'));return issues;}
function qualityCounts(report=qualityReport){const issues=report?.issues||[];return{error:issues.filter(x=>x.severity==='error').length,warning:issues.filter(x=>x.severity==='warning').length,info:issues.filter(x=>x.severity==='info').length};}
function qualityBadgeHtml(slideIndex){if(!qualityReport||qualityReport.stale)return'';const list=qualityReport.issues.filter(x=>x.slideIndex===slideIndex),errors=list.filter(x=>x.severity==='error').length,warnings=list.filter(x=>x.severity==='warning').length;if(errors)return`<span class="thumb-quality error" title="${errors} errori">${errors}</span>`;if(warnings)return`<span class="thumb-quality warning" title="${warnings} avvisi">${warnings}</span>`;return`<span class="thumb-quality ok" title="Slide controllata">✓</span>`;}
function renderQualityPanel(){const badge=$('qualityStatusBadge'),checked=$('qualityCheckedAt'),metrics=$('qualityMetrics'),list=$('qualityList'),first=$('fixFirstQualityBtn');if(!badge||!checked||!metrics||!list)return;if(!qualityReport){badge.className='quality-status neutral';badge.textContent='Da controllare';checked.textContent='Non ancora eseguito';metrics.innerHTML='<span>— errori</span><span>— avvisi</span><span>— note</span>';list.innerHTML='<p class="panel-note">Il controllo verifica testi, margini, risoluzione delle immagini, logo, livelli nascosti e coerenza del progetto.</p>';if(first)first.disabled=true;return;}const c=qualityCounts();checked.textContent=qualityReport.stale?'Modificato dopo l’ultimo controllo':`Controllato alle ${new Date(qualityReport.checkedAt).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}`;badge.className=`quality-status ${qualityReport.stale?'stale':c.error?'error':c.warning?'warning':'ok'}`;badge.textContent=qualityReport.stale?'Da aggiornare':c.error?`${c.error} errori`:c.warning?`${c.warning} avvisi`:'Pronto';metrics.innerHTML=`<span>${c.error} errori</span><span>${c.warning} avvisi</span><span>${c.info} note</span>`;if(first)first.disabled=!qualityReport.issues.length;if(!qualityReport.issues.length){list.innerHTML='<div class="quality-empty">✓ Nessun problema rilevato. Il carosello è pronto per l’esportazione.</div>';return;}list.innerHTML=qualityReport.issues.map((issue,index)=>`<button class="quality-issue ${issue.severity}" type="button" data-quality-index="${index}"><span class="quality-icon">${issue.severity==='error'?'!':issue.severity==='warning'?'△':'i'}</span><span class="quality-copy"><strong>${esc(issue.title)}</strong><small>${esc(issue.message)}</small></span><span class="quality-slide-tag">S${issue.slideIndex+1}</span></button>`).join('');}
function jumpToQualityIssue(issue){if(!issue)return;currentIndex=clamp(issue.slideIndex,0,project.slides.length-1);const slide=currentSlide();if(issue.key&&elementModel(slide,issue.key))selected=issue.key;render();setTab(issue.key==='image'||String(issue.key).startsWith('overlay:')?'images':issue.key==='title'||issue.key==='subtitle'||String(issue.key).startsWith('free:')?'style':'layers');showToast(`Slide ${currentIndex+1}: ${issue.title}`);}
async function runQualityCheck({focusPanel=true}={}){try{if(focusPanel)setTab('export');$('runQualityBtn').disabled=true;$('runQualityBtn').textContent='Controllo…';await ensureExportFonts();const issues=[];for(let i=0;i<project.slides.length;i++){$('saveStatus').textContent=`controllo ${i+1}/${project.slides.length}`;issues.push(...await analyzeSlideQuality(project.slides[i],i));}issues.push(...projectQualityIssues());qualityReport={issues,checkedAt:Date.now(),stale:false};renderQualityPanel();renderFilmstrip();const c=qualityCounts();$('saveStatus').textContent='salvato sul dispositivo';showToast(c.error?`${c.error} errori da correggere`:c.warning?`${c.warning} avvisi da verificare`:'Carosello pronto');return qualityReport;}finally{if($('runQualityBtn')){$('runQualityBtn').disabled=false;$('runQualityBtn').textContent='Controlla carosello';}}}
function qualityReportText(report=qualityReport){if(!report)return'Controllo qualità non eseguito.';const c=qualityCounts(report),lines=[`CdB Studio — rapporto qualità`,`Progetto: ${project.name}`,`Data: ${new Date(report.checkedAt).toLocaleString('it-IT')}`,`Errori: ${c.error} | Avvisi: ${c.warning} | Note: ${c.info}`,''];for(const issue of report.issues)lines.push(`[${issue.severity.toUpperCase()}] Slide ${issue.slideIndex+1} — ${issue.title}: ${issue.message}`);if(!report.issues.length)lines.push('Nessun problema rilevato.');return lines.join('\n');}
function showQualityGuardDialog(report,label){const c=qualityCounts(report),dialog=$('qualityDialog');$('qualityDialogCopy').textContent=`Prima di ${label} sono stati trovati ${c.error} errori e ${c.warning} avvisi.`;$('qualityDialogMetrics').innerHTML=`<span>${c.error} errori</span><span>${c.warning} avvisi</span><span>${c.info} note</span>`;dialog.showModal();}
async function withQualityGuard(label,action){let report=qualityReport;if($('autoQualityInput')?.checked&&(!report||report.stale))report=await runQualityCheck({focusPanel:false});const c=qualityCounts(report);if(report&&(c.error||c.warning)) {pendingQualityExport=action;showQualityGuardDialog(report,label);return;}await action();}
async function exportCompletePackage(){
  let report=qualityReport;if(!report||report.stale)report=await runQualityCheck({focusPanel:false});
  const files=[],affinityFontDataUrl=await loadAffinityFontDataUrl(),affinityLogoMarkup=await loadAffinityLogoMarkup();
  const failures=[];
  for(let i=0;i<project.slides.length;i++){
    const base=`${String(i+1).padStart(2,'0')}-${slug(project.slides[i].title?.text||`slide-${i+1}`).slice(0,44)}`;
    $('saveStatus').textContent=`pacchetto ${i+1}/${project.slides.length}`;
    try{files.push({name:`png/${base}.png`,blob:await withTimeout(renderPngBlob(project.slides[i]),30000,`PNG slide ${i+1}`)});files.push({name:`svg/${base}.svg`,blob:new Blob([buildAffinitySvg(project.slides[i],{suffix:`package${i}`,fontDataUrl:affinityFontDataUrl,logoMarkup:affinityLogoMarkup})],{type:'image/svg+xml;charset=utf-8'})});}catch(error){failures.push({slide:i+1,error:error.message});diagnosticLog('error','export-package',`Slide ${i+1} saltata`,error);}await nextFrame();
  }
  const portable=await buildPortableProjectPackage({statusPrefix:'Incorporo le immagini nel progetto'});
  files.push({name:`${slug(project.name)}.cdbproject.zip`,blob:portable.blob});
  files.push({name:`${slug(project.name)}.cdb.json`,blob:new Blob([JSON.stringify(project,null,2)],{type:'application/json'})});
  files.push({name:'rapporto-qualita.txt',blob:new Blob([qualityReportText(report)],{type:'text/plain;charset=utf-8'})});
  if(diagnosticsReport)files.push({name:'rapporto-diagnostica.txt',blob:new Blob([diagnosticReportText(diagnosticsReport)],{type:'text/plain;charset=utf-8'})});
  files.push({name:'fonti-immagini.txt',blob:new Blob([imageSourcesReport()],{type:'text/plain;charset=utf-8'})});
  if(failures.length)files.push({name:'errori-export.txt',blob:new Blob([failures.map(item=>`Slide ${item.slide}: ${item.error}`).join('\n')],{type:'text/plain;charset=utf-8'})});
  const portableNote=portable.unresolved.length?`\nAttenzione: ${portable.unresolved.length} immagini esterne non sono state incorporate nel progetto portatile.\n`:'';
  files.push({name:'LEGGIMI.txt',blob:new Blob([`Cartella png: file pronti per la pubblicazione.\nCartella svg: versioni modificabili e ottimizzate per Affinity, con Nickel Gothic incorporato.\nIl file .cdbproject.zip contiene progetto, immagini, ritagli e layout per continuare su Mac o iPhone.\nIl file .cdb.json è una copia leggera di compatibilità e può dipendere da immagini online.\nfonti-immagini.txt raccoglie provenienza e licenza dichiarata delle immagini. Se hai eseguito la diagnostica, il pacchetto include anche rapporto-diagnostica.txt.${portableNote}`],{type:'text/plain;charset=utf-8'})});
  downloadBlob(await makeZip(files),`${slug(project.name)}-pacchetto.zip`);$('saveStatus').textContent='salvato sul dispositivo';
}

async function exportCarouselZip(){const files=[],failures=[];for(let i=0;i<project.slides.length;i++){$('saveStatus').textContent=`esporto ${i+1}/${project.slides.length}`;const base=`${String(i+1).padStart(2,'0')}-${slug(project.slides[i].title?.text||`slide-${i+1}`).slice(0,44)}`;try{files.push({name:`${base}.png`,blob:await withTimeout(renderPngBlob(project.slides[i]),30000,`PNG slide ${i+1}`)});}catch(error){failures.push({slide:i+1,error:error.message});diagnosticLog('error','export-zip',`Slide ${i+1} saltata`,error);}await nextFrame();}if(!files.length)throw new Error('Nessuna slide esportabile. Controlla immagini e memoria disponibile.');if(failures.length)files.push({name:'errori-export.txt',blob:new Blob([failures.map(item=>`Slide ${item.slide}: ${item.error}`).join('\n')],{type:'text/plain;charset=utf-8'})});downloadBlob(await makeZip(files),`${slug(project.name)}.zip`);$('saveStatus').textContent=failures.length?`ZIP pronto · ${failures.length} slide saltate`:'salvato sul dispositivo';return failures;}

async function renderPngBlob(slide){
  await Promise.all([{name:'Nickel Gothic v3',weight:400},{name:'Anton',weight:400},{name:'Anybody',weight:800},{name:'Archivo',weight:800},{name:'Saira',weight:800}].map(f=>document.fonts?.load(`${f.weight} 90px "${f.name}"`).catch(()=>null))||[]);
  ensureLayerModel(slide);const out=document.createElement('canvas');out.width=W;out.height=H;const ctx=out.getContext('2d');
  if(layerVisible(slide,TEMPLATE_BACK_KEY)){ctx.save();ctx.globalAlpha=layerOpacity(slide,TEMPLATE_BACK_KEY);drawTemplateBackCanvas(ctx,slide);ctx.restore();}
  for(const key of slide.layerOrder)await drawElementLayerCanvas(ctx,slide,key);
  return new Promise((resolve,reject)=>out.toBlob(b=>b?resolve(b):reject(new Error('PNG non creato')),'image/png'));
}
function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1600);}
const crcTable=(()=>{const t=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0;}return t;})();
function crc32(bytes){let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0;}
function u16(n){return new Uint8Array([n&255,(n>>>8)&255]);}function u32(n){return new Uint8Array([n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255]);}
function concatArrays(parts){const len=parts.reduce((s,p)=>s+p.length,0),out=new Uint8Array(len);let o=0;for(const p of parts){out.set(p,o);o+=p.length;}return out;}
async function makeZip(files){const enc=new TextEncoder(),local=[],central=[];let offset=0;for(const file of files){const name=enc.encode(file.name),data=new Uint8Array(await file.blob.arrayBuffer()),crc=crc32(data),lh=concatArrays([u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),name]);local.push(lh,data);const ch=concatArrays([u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name]);central.push(ch);offset+=lh.length+data.length;}const cd=concatArrays(central),ld=concatArrays(local),end=concatArrays([u32(0x06054b50),u16(0),u16(0),u16(files.length),u16(files.length),u32(cd.length),u32(ld.length),u16(0)]);return new Blob([ld,cd,end],{type:'application/zip'});}

function projectAssetReferences(targetProject){
  const refs=[];
  for(const [slideIndex,slide] of (targetProject?.slides||[]).entries()){
    if(slide?.image?.src)refs.push({container:slide.image,key:'src',slideIndex,label:`Slide ${slideIndex+1} · immagine principale`});
    for(const [overlayIndex,overlay] of (slide?.overlays||[]).entries())if(overlay?.src)refs.push({container:overlay,key:'src',slideIndex,label:`Slide ${slideIndex+1} · ${overlay.name||`immagine libera ${overlayIndex+1}`}`});
    if(slide?.instagramReference?.src)refs.push({container:slide.instagramReference,key:'src',slideIndex,label:`Slide ${slideIndex+1} · screenshot Instagram di riferimento`});
  }
  return refs;
}
function formatBytes(value){const bytes=Number(value||0);if(bytes<1024)return`${bytes} B`;if(bytes<1024*1024)return`${(bytes/1024).toFixed(bytes<10240?1:0)} KB`;return`${(bytes/1024/1024).toFixed(bytes<10*1024*1024?1:0)} MB`;}
function projectTransferStatus(message,kind=''){const el=$('projectTransferStatus');if(!el)return;el.textContent=message;el.className=`inline-status${kind?' '+kind:''}`;}
function extensionForImageBlob(blob,src=''){
  const mime=String(blob?.type||'').toLowerCase();if(mime.includes('png'))return'png';if(mime.includes('webp'))return'webp';if(mime.includes('gif'))return'gif';if(mime.includes('svg'))return'svg';if(mime.includes('avif'))return'avif';if(mime.includes('jpeg')||mime.includes('jpg'))return'jpg';
  const ext=String(src).match(/\.([a-z0-9]{2,5})(?:[?#]|$)/i)?.[1]?.toLowerCase();return['png','webp','gif','svg','avif','jpg','jpeg'].includes(ext)?(ext==='jpeg'?'jpg':ext):'jpg';
}
function mimeForExtension(ext){return({png:'image/png',webp:'image/webp',gif:'image/gif',svg:'image/svg+xml',avif:'image/avif',jpg:'image/jpeg',jpeg:'image/jpeg'})[String(ext).toLowerCase()]||'application/octet-stream';}
async function portableSourceBlob(src){
  if(!src)throw new Error('Sorgente vuota');
  const response=await fetch(src,{cache:'no-store'});if(!response.ok&&response.type!=='opaque')throw new Error(`HTTP ${response.status}`);if(response.type==='opaque')throw new Error('Il server non consente di incorporare il file');
  const blob=await response.blob();if(!blob.size)throw new Error('File vuoto');if(blob.type&&!blob.type.startsWith('image/'))throw new Error(`Formato ${blob.type} non supportato`);return blob;
}
async function buildPortableProjectPackage({statusPrefix='Preparo il progetto portatile'}={}){
  const portableProject=deepClone(project);portableProject.version=APP_VERSION;
  portableProject.transfer={format:PORTABLE_PROJECT_FORMAT,schema:PORTABLE_PROJECT_SCHEMA,createdAt:new Date().toISOString(),sourceDevice:navigator.userAgent||''};
  const refs=projectAssetReferences(portableProject),files=[],assets=[],unresolved=[],sourceMap=new Map();
  for(let index=0;index<refs.length;index++){
    const ref=refs[index],src=ref.container[ref.key];projectTransferStatus(`${statusPrefix}: ${index+1}/${refs.length}`,'working');$('saveStatus').textContent=`immagini ${index+1}/${refs.length}`;
    if(sourceMap.has(src)){const prior=sourceMap.get(src);ref.container[ref.key]=`cdbpack://${prior.file}`;continue;}
    try{
      const blob=await portableSourceBlob(src),ext=extensionForImageBlob(blob,src),id=`asset-${String(assets.length+1).padStart(3,'0')}-${imageAssetKey(src).split(':').pop()}`,file=`assets/${id}.${ext}`;
      files.push({name:file,blob});assets.push({id,file,mime:blob.type||mimeForExtension(ext),bytes:blob.size,label:ref.label,originalSource:String(src).startsWith('data:')?'embedded-data':src});sourceMap.set(src,{file});ref.container[ref.key]=`cdbpack://${file}`;
    }catch(error){unresolved.push({slide:ref.slideIndex+1,label:ref.label,source:src,error:error?.message||String(error)});}
  }
  const manifest={format:PORTABLE_PROJECT_FORMAT,schema:PORTABLE_PROJECT_SCHEMA,appVersion:APP_VERSION,createdAt:new Date().toISOString(),projectFile:'project.json',projectName:project.name,slides:portableProject.slides.length,assets,unresolved};
  files.unshift({name:'project.json',blob:new Blob([JSON.stringify(portableProject,null,2)],{type:'application/json;charset=utf-8'})});
  files.unshift({name:'manifest.json',blob:new Blob([JSON.stringify(manifest,null,2)],{type:'application/json;charset=utf-8'})});
  const blob=await makeZip(files);return{blob,manifest,unresolved,assetCount:assets.length,size:blob.size,fileName:`${slug(project.name)}.cdbproject.zip`};
}
async function confirmPortableCompleteness(result){
  if(!result.unresolved.length)return true;
  const examples=result.unresolved.slice(0,3).map(item=>`• ${item.label}`).join('\n');
  return confirm(`${result.unresolved.length} immagini non possono essere incorporate dal browser. Il progetto si aprirà, ma quelle immagini potrebbero dipendere ancora dalla rete.\n\n${examples}\n\nSalvare comunque?`);
}
async function savePortableProject({share=false}={}){
  const buttons=[$('exportProjectBtn'),$('shareProjectBtn')].filter(Boolean);buttons.forEach(button=>button.disabled=true);
  try{
    projectTransferStatus('Raccolgo immagini, ritagli e livelli…','working');const result=await buildPortableProjectPackage();if(!await confirmPortableCompleteness(result)){projectTransferStatus('Esportazione annullata: sostituisci le immagini non incorporabili.','warning');return;}
    const file=new File([result.blob],result.fileName,{type:'application/zip'});
    if(share&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:project.name,text:'Progetto CdB Studio portatile'});projectTransferStatus(`Condiviso: ${result.assetCount} immagini · ${formatBytes(result.size)}`,'success');showToast('Progetto condiviso');}
    else{downloadBlob(result.blob,result.fileName);projectTransferStatus(`Salvato: ${result.assetCount} immagini · ${formatBytes(result.size)}${result.unresolved.length?` · ${result.unresolved.length} da verificare`:''}`,result.unresolved.length?'warning':'success');showToast(share?'Condivisione non disponibile: progetto scaricato':'Progetto portatile pronto');}
  }catch(error){if(error?.name!=='AbortError'){console.error(error);projectTransferStatus(`Errore: ${error?.message||'progetto non creato'}`,'error');showToast('Progetto portatile non creato');}}
  finally{buttons.forEach(button=>button.disabled=false);$('saveStatus').textContent='salvato sul dispositivo';}
}
function readZipU16(view,offset){return view.getUint16(offset,true);}function readZipU32(view,offset){return view.getUint32(offset,true);}
function parseStoredZip(arrayBuffer){
  const bytes=new Uint8Array(arrayBuffer),view=new DataView(arrayBuffer),decoder=new TextDecoder();let eocd=-1;for(let i=Math.max(0,bytes.length-65557);i<=bytes.length-22;i++)if(readZipU32(view,i)===0x06054b50)eocd=i;if(eocd<0)throw new Error('Archivio ZIP non riconosciuto');
  const count=readZipU16(view,eocd+10),centralOffset=readZipU32(view,eocd+16),entries=new Map();let cursor=centralOffset;
  for(let index=0;index<count;index++){
    if(readZipU32(view,cursor)!==0x02014b50)throw new Error('Indice ZIP non valido');const method=readZipU16(view,cursor+10),compressedSize=readZipU32(view,cursor+20),nameLength=readZipU16(view,cursor+28),extraLength=readZipU16(view,cursor+30),commentLength=readZipU16(view,cursor+32),localOffset=readZipU32(view,cursor+42),name=decoder.decode(bytes.slice(cursor+46,cursor+46+nameLength));
    if(method!==0)throw new Error('Questo progetto è stato ricompresso. Usa il file .cdbproject.zip originale.');if(readZipU32(view,localOffset)!==0x04034b50)throw new Error('File ZIP danneggiato');const localNameLength=readZipU16(view,localOffset+26),localExtraLength=readZipU16(view,localOffset+28),dataStart=localOffset+30+localNameLength+localExtraLength;entries.set(name,bytes.slice(dataStart,dataStart+compressedSize));cursor+=46+nameLength+extraLength+commentLength;
  }
  return entries;
}
function zipEntryText(entries,name){const bytes=entries.get(name);if(!bytes)throw new Error(`Manca ${name}`);return new TextDecoder().decode(bytes);}
async function activateProjectData(raw,{sourceName='progetto',transfer=null}={}){
  let parsed=migrateLegacyProject(raw);if(!Array.isArray(parsed?.slides)||!parsed.slides.length)throw new Error('Formato progetto non valido');
  project={...parsed,version:APP_VERSION,showNumbers:Boolean(parsed.showNumbers),snapGuides:parsed.snapGuides!==false,slides:parsed.slides.map(normalizeSlide)};project.slides.forEach((slide,index)=>ensureSlideImageQuery(slide,index));
  const refs=projectAssetReferences(project);await Promise.all(refs.map(ref=>hydrateImageMeta(ref.container).catch(()=>ref.container)));
  if(transfer)project.transfer={...(project.transfer||{}),importedAt:new Date().toISOString(),sourceName,...transfer};
  currentIndex=0;selected='title';history=[];historyIndex=-1;commitHistory();render();setTab('quick');return project;
}
async function importPortableProjectZip(file){
  projectTransferStatus('Apro il progetto e ricostruisco le immagini…','working');const entries=parseStoredZip(await file.arrayBuffer()),manifest=JSON.parse(zipEntryText(entries,'manifest.json'));
  if(manifest.format!==PORTABLE_PROJECT_FORMAT)throw new Error('Non è un progetto portatile CdB Studio');if(Number(manifest.schema)>PORTABLE_PROJECT_SCHEMA)throw new Error('Il progetto richiede una versione più recente dell’app');
  const raw=JSON.parse(zipEntryText(entries,manifest.projectFile||'project.json')),assetMeta=new Map((manifest.assets||[]).map(item=>[item.file,item])),refs=projectAssetReferences(raw);let restored=0;
  for(const ref of refs){const src=String(ref.container[ref.key]||'');if(!src.startsWith('cdbpack://'))continue;const path=src.slice('cdbpack://'.length),bytes=entries.get(path);if(!bytes)throw new Error(`Immagine mancante: ${path}`);const meta=assetMeta.get(path),ext=path.split('.').pop(),blob=new Blob([bytes],{type:meta?.mime||mimeForExtension(ext)});ref.container[ref.key]=await blobToDataUrl(blob);restored++;projectTransferStatus(`Ripristino immagini: ${restored}/${manifest.assets?.length||restored}`,'working');}
  await activateProjectData(raw,{sourceName:file.name,transfer:{format:manifest.format,schema:manifest.schema,restoredAssets:restored,unresolvedAssets:(manifest.unresolved||[]).length}});projectTransferStatus(`Progetto aperto: ${restored} immagini incorporate${manifest.unresolved?.length?` · ${manifest.unresolved.length} fonti esterne`:''}`,manifest.unresolved?.length?'warning':'success');showToast('Progetto portatile aperto');
}
async function importProjectFile(file){
  const header=new Uint8Array(await file.slice(0,4).arrayBuffer());if(header[0]===0x50&&header[1]===0x4b)return importPortableProjectZip(file);
  const raw=JSON.parse(await file.text());if(!isProjectJsonPayload(raw)&&isContentJsonPayload(raw))return activateContentJson(raw,file.name);await activateProjectData(raw,{sourceName:file.name});projectTransferStatus('Progetto JSON aperto. Le immagini online non sono incorporate.','warning');showToast('Progetto aperto');
}

function isProjectJsonPayload(raw){if(raw?.client?.st&&Array.isArray(raw.slides))return true;if(!Array.isArray(raw?.slides)||!raw.slides.length)return false;return raw.slides.some(slide=>Boolean(slide?.family||slide?.variant||slide?.title?.text!==undefined||slide?.subtitle?.text!==undefined||slide?.layerSchemaVersion||slide?.layerOrder));}



async function exportFaithfulSvg(){const blob=await renderPngBlob(currentSlide());const data=await blobToDataUrl(blob);const svg=`<svg xmlns="${SVG_NS}" width="1080" height="1350" viewBox="0 0 1080 1350"><image href="${data}" width="1080" height="1350"/></svg>`;downloadBlob(new Blob([svg],{type:'image/svg+xml;charset=utf-8'}),`${slug(project.name)}-${currentIndex+1}-fedele.svg`);}
async function exportPdf(){if(!window.PDFLib)await loadExternalScript('https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/dist/pdf-lib.min.js','PDFLib',{timeout:20000});if(!window.PDFLib)throw new Error('Motore PDF non disponibile. Controlla la connessione e riprova.');const pdf=await PDFLib.PDFDocument.create();const failures=[];for(let i=0;i<project.slides.length;i++){$('saveStatus').textContent=`PDF ${i+1}/${project.slides.length}`;try{const png=await withTimeout(renderPngBlob(project.slides[i]),30000,`Slide ${i+1}`),bytes=await png.arrayBuffer(),image=await pdf.embedPng(bytes),page=pdf.addPage([W,H]);page.drawImage(image,{x:0,y:0,width:W,height:H});}catch(error){failures.push(i+1);diagnosticLog('error','export-pdf',`Slide ${i+1} saltata`,error);}await nextFrame();}if(!pdf.getPageCount())throw new Error('Nessuna slide esportabile. Controlla le immagini e riprova.');const bytes=await pdf.save();downloadBlob(new Blob([bytes],{type:'application/pdf'}),`${slug(project.name)}.pdf`);$('saveStatus').textContent=failures.length?`PDF pronto · ${failures.length} slide saltate`:'salvato sul dispositivo';if(failures.length)showToast(`PDF creato; slide saltate: ${failures.join(', ')}`);}


function diagnosticResult(id,label,status,detail='',value=''){return{id,label,status,detail:String(detail||''),value:String(value||'')};}
function diagnosticStatusRank(status){return status==='fail'?3:status==='warn'?2:status==='info'?1:0;}
function withDiagnosticTimeout(promise,ms,label='Operazione'){return Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error(`${label}: tempo scaduto`)),ms))]);}
function formatDiagnosticBytes(value){return formatBytes(Math.max(0,Number(value)||0));}
function dataUrlApproxBytes(src=''){if(!String(src).startsWith('data:'))return 0;const comma=src.indexOf(',');if(comma<0)return 0;const body=src.slice(comma+1);return /;base64/i.test(src.slice(0,comma))?Math.floor(body.length*.75):new Blob([decodeURIComponent(body)]).size;}
function projectEmbeddedBytes(){let total=0;for(const slide of project?.slides||[]){total+=dataUrlApproxBytes(slide.image?.src);for(const ov of slide.overlays||[])total+=dataUrlApproxBytes(ov.src);total+=dataUrlApproxBytes(slide.instagramReference?.src);}return total;}
function diagnosticsIcon(status){return status==='pass'?'✓':status==='fail'?'×':status==='warn'?'!':'i';}
function renderDiagnosticsPanel(report=diagnosticsReport){
  const list=$('diagnosticsList'),badge=$('diagnosticsStatusBadge'),summary=$('diagnosticsSummary');if(!list||!badge||!summary)return;
  if(!report){badge.textContent='Mai eseguita';badge.className='quality-status neutral';return;}
  const fail=report.results.filter(x=>x.status==='fail').length,warn=report.results.filter(x=>x.status==='warn').length,pass=report.results.filter(x=>x.status==='pass').length,info=report.results.filter(x=>x.status==='info').length;
  badge.textContent=fail?`${fail} errori`:warn?`${warn} avvisi`:'Tutto operativo';badge.className=`quality-status ${fail?'error':warn?'warning':'ok'}`;
  summary.textContent=`${pass} superati · ${warn} avvisi · ${fail} errori · ${info} informazioni · ${new Date(report.createdAt).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}`;summary.className=`inline-status ${fail?'error':warn?'warning':'success'}`;
  list.innerHTML=report.results.map(item=>`<div class="diagnostic-item ${item.status}"><span class="diagnostic-icon">${diagnosticsIcon(item.status)}</span><div class="diagnostic-copy"><strong>${esc(item.label)}</strong><small>${esc(item.detail)}</small></div>${item.value?`<span class="diagnostic-value">${esc(item.value)}</span>`:''}</div>`).join('');
  if($('copyDiagnosticsBtn'))$('copyDiagnosticsBtn').disabled=false;if($('downloadDiagnosticsBtn'))$('downloadDiagnosticsBtn').disabled=false;
}
function diagnosticReportText(report=diagnosticsReport){
  if(!report)return 'Nessuna diagnostica eseguita.';
  const lines=[`CdB Studio v${APP_VERSION} · rapporto diagnostico`,report.createdAt,`Pagina: ${location.origin}${location.pathname}`,`Browser: ${navigator.userAgent}`,`Online: ${navigator.onLine?'sì':'no'}`,''];
  for(const item of report.results)lines.push(`[${item.status.toUpperCase()}] ${item.label}${item.value?` · ${item.value}`:''}\n${item.detail}`);
  if(report.runtimeIssues.length){lines.push('','Errori runtime recenti:');for(const issue of report.runtimeIssues)lines.push(`- ${issue.at} · ${issue.area||issue.kind}: ${issue.message}`);}else lines.push('','Errori runtime recenti: nessuno registrato.');
  lines.push('','Nota: il rapporto non contiene la chiave TMDb né il PIN locale.');return lines.join('\n');
}
async function diagnosticLocalStorage(){const key='cdb-diagnostic-local-storage';try{localStorage.setItem(key,'ok');const ok=localStorage.getItem(key)==='ok';localStorage.removeItem(key);return diagnosticResult('localStorage','Impostazioni locali',ok?'pass':'fail',ok?'Scrittura, lettura e cancellazione funzionano.':'Il browser non ha restituito il valore scritto.');}catch(error){return diagnosticResult('localStorage','Impostazioni locali','fail',error.message);}}
async function diagnosticIndexedDb(){const key='__diagnostic__';try{const value={at:Date.now(),version:APP_VERSION};await storePut('projects',key,value);const saved=await storeGet('projects',key);await storeDelete('projects',key);return diagnosticResult('indexedDb','Salvataggio progetti',saved?.version===APP_VERSION?'pass':'fail',saved?.version===APP_VERSION?'IndexedDB scrive, legge e cancella correttamente.':'Lettura di verifica non coerente.');}catch(error){return diagnosticResult('indexedDb','Salvataggio progetti','fail',error.message);}}
async function diagnosticStorageAndMemory(){
  const embedded=projectEmbeddedBytes(),jsonBytes=new Blob([JSON.stringify(project||{})]).size;let detail=`Progetto JSON ${formatDiagnosticBytes(jsonBytes)}; immagini incorporate ${formatDiagnosticBytes(embedded)}.`;let status=(embedded>80*1024*1024||jsonBytes>8*1024*1024)?'warn':'pass',value=formatDiagnosticBytes(jsonBytes+embedded);
  try{if(navigator.storage?.estimate){const est=await navigator.storage.estimate(),ratio=est.quota?est.usage/est.quota:0;detail+=` Archivio browser ${formatDiagnosticBytes(est.usage)} su ${formatDiagnosticBytes(est.quota)}.`;if(ratio>.8)status='warn';}}
  catch(error){detail+=` Stima archivio non disponibile: ${error.message}.`;if(status==='pass')status='info';}
  if(navigator.deviceMemory)detail+=` Memoria dispositivo dichiarata: ${navigator.deviceMemory} GB.`;
  return diagnosticResult('memory','Memoria e spazio',status,detail,value);
}
async function diagnosticBrowser(){const required={fetch:typeof fetch==='function',Promise:typeof Promise==='function',FileReader:typeof FileReader==='function',Blob:typeof Blob==='function',TextEncoder:typeof TextEncoder==='function',Canvas:Boolean(document.createElement('canvas').getContext),SVG:Boolean(document.createElementNS?.(SVG_NS,'svg')),Crypto:Boolean(crypto?.subtle)};const missing=Object.entries(required).filter(([,ok])=>!ok).map(([name])=>name),local=['localhost','127.0.0.1'].includes(location.hostname),secure=window.isSecureContext||local,value=location.protocol==='https:'?'HTTPS':local?'localhost':'HTTP';return diagnosticResult('browser','Compatibilità browser',missing.length?'fail':secure?'pass':'warn',missing.length?`Funzioni mancanti: ${missing.join(', ')}.`:secure?'Le funzioni essenziali dell’editor sono disponibili.':'L’app non è in un contesto sicuro: clipboard e service worker possono essere limitati.',value);}
async function diagnosticNetwork(){try{const response=await withDiagnosticTimeout(fetch(`version.json?diagnostic=${Date.now()}`,{cache:'no-store'}),7000,'Rete');const payload=await response.json();return diagnosticResult('network','Connessione e file app',response.ok&&payload.version?'pass':'fail',response.ok?`version.json raggiungibile; versione pubblicata ${payload.version}.`:`HTTP ${response.status}.`,navigator.onLine?'online':'offline');}catch(error){return diagnosticResult('network','Connessione e file app',navigator.onLine?'fail':'warn',error.message,navigator.onLine?'online':'offline');}}
async function diagnosticFonts(){try{if(!document.fonts)return diagnosticResult('fonts','Font','warn','Font Loading API non disponibile: la resa va controllata visivamente.');await withDiagnosticTimeout(document.fonts.ready,5000,'Font');const nickel=document.fonts.check('24px "Nickel Gothic v3"'),archivo=document.fonts.check('24px Archivo');return diagnosticResult('fonts','Font',nickel?'pass':'warn',nickel?`Nickel Gothic v3 caricato${archivo?' insieme ad Archivo':''}.`:'Nickel Gothic v3 non risulta caricato; il browser userà un font di riserva.',nickel?'Nickel Gothic OK':'fallback');}catch(error){return diagnosticResult('fonts','Font','warn',error.message);}}
async function diagnosticPngExport(){try{const blob=await withDiagnosticTimeout(renderPngBlob(currentSlide()),12000,'Export PNG');const ok=blob.type==='image/png'&&blob.size>5000;return diagnosticResult('png','Motore PNG',ok?'pass':'fail',ok?'La slide corrente viene rasterizzata correttamente.':'Il file generato è vuoto o troppo piccolo.',formatDiagnosticBytes(blob.size));}catch(error){return diagnosticResult('png','Motore PNG','fail',error.message);}}
async function diagnosticZip(){try{const blob=await makeZip([{name:'diagnostica.txt',blob:new Blob(['CdB Studio'],{type:'text/plain'})}]);return diagnosticResult('zip','Motore ZIP',blob.size>30?'pass':'fail',blob.size>30?'Creazione archivio disponibile.':'Archivio non valido.',formatDiagnosticBytes(blob.size));}catch(error){return diagnosticResult('zip','Motore ZIP','fail',error.message);}}
async function diagnosticServiceWorker(){
  if(!('serviceWorker'in navigator))return diagnosticResult('sw','Cache offline','warn','Service worker non supportato da questo browser.');
  if(!location.protocol.startsWith('http'))return diagnosticResult('sw','Cache offline','warn','Apri l’app tramite HTTPS o localhost per usare la cache offline.');
  try{let registration=await navigator.serviceWorker.getRegistration('./');if(!registration)registration=await navigator.serviceWorker.register(`./sw.js?v=${APP_VERSION}`);await withDiagnosticTimeout(registration.update(),7000,'Aggiornamento service worker');const controlled=Boolean(navigator.serviceWorker.controller);const keys=typeof caches!=='undefined'?await caches.keys():[];const current=keys.includes(`cdb-studio-v${APP_VERSION}`);return diagnosticResult('sw','Cache offline',registration?'pass':'fail',`${registration.active?'Service worker attivo':'Service worker registrato'}; pagina ${controlled?'controllata':'non ancora controllata fino al prossimo avvio'}; cache ${current?'presente':'in preparazione'}.`,current?'cache OK':'riapri app');}catch(error){return diagnosticResult('sw','Cache offline','fail',error.message);}
}
async function diagnosticOcr(){try{const already=Boolean(window.Tesseract?.createWorker);if(!already)await withDiagnosticTimeout(loadExternalScript(DIAGNOSTIC_OCR_CDN,'Tesseract'),12000,'Caricamento OCR');const ok=Boolean(window.Tesseract?.createWorker);return diagnosticResult('ocr','Motore OCR',ok?'pass':'fail',ok?`${already?'Motore già caricato':'CDN raggiungibile e motore caricato'}. I modelli italiano/inglese vengono scaricati al primo OCR.`:'Tesseract non espone createWorker.',ok?'Tesseract 6':'non disponibile');}catch(error){return diagnosticResult('ocr','Motore OCR','fail',`Il browser non riesce a caricare Tesseract: ${error.message}`);}}
async function diagnosticTmdb(){if(!tmdbKey.trim())return diagnosticResult('tmdb','TMDb','info','Nessuna chiave configurata. La ricerca userà le altre fonti disponibili.','non configurato');try{const data=await withDiagnosticTimeout(tmdbFetch('configuration'),9000,'TMDb');return diagnosticResult('tmdb','TMDb',data?.images?.secure_base_url?'pass':'warn',data?.images?.secure_base_url?'Chiave valida e API raggiungibile.':'Risposta ricevuta ma configurazione immagini incompleta.','API OK');}catch(error){return diagnosticResult('tmdb','TMDb','fail',`Chiave o connessione non valide: ${error.message}`);}}
async function diagnosticExternalImage(){const src=currentSlide()?.image?.src||'';if(!src)return diagnosticResult('externalImage','Immagine corrente','info','La slide corrente non contiene un’immagine da verificare.');if(src.startsWith('data:')||src.startsWith('blob:'))return diagnosticResult('externalImage','Immagine corrente','pass','Immagine locale o incorporata: non dipende da un server esterno.',src.startsWith('data:')?'incorporata':'locale');if(!/^https?:/i.test(src))return diagnosticResult('externalImage','Immagine corrente','info','Percorso locale o formato non remoto.',src.slice(0,40));try{const response=await withDiagnosticTimeout(fetch(src,{mode:'cors',cache:'no-store'}),9000,'Immagine esterna');const blob=await response.blob();return diagnosticResult('externalImage','Immagine corrente',response.ok&&blob.type.startsWith('image/')?'pass':'warn',response.ok?`Il server consente l’importazione CORS (${blob.type||'tipo non dichiarato'}).`:`HTTP ${response.status}.`,formatDiagnosticBytes(blob.size));}catch(error){return diagnosticResult('externalImage','Immagine corrente','warn',`Visibile nel browser ma non incorporabile automaticamente: ${error.message}`,'CORS bloccato');}}
async function diagnosticRuntime(){const recent=runtimeIssueLog.filter(x=>x.level==='error').slice(-8);return diagnosticResult('runtime','Errori runtime',recent.length?'warn':'pass',recent.length?recent.map(x=>`${x.area||x.kind}: ${x.message}`).join(' · '):'Nessun errore JavaScript registrato in questa sessione.',recent.length?`${recent.length} eventi`:'pulito');}
async function runDiagnostics(){
  const button=$('runDiagnosticsBtn');if(button)button.disabled=true;$('diagnosticsStatusBadge').textContent='Controllo…';$('diagnosticsStatusBadge').className='quality-status stale';$('diagnosticsSummary').textContent='Eseguo i controlli sul dispositivo…';$('diagnosticsSummary').className='inline-status working';$('diagnosticsList').innerHTML='<p class="panel-note">Browser e salvataggio…</p>';
  const results=[];const checks=[diagnosticBrowser,diagnosticLocalStorage,diagnosticIndexedDb,diagnosticStorageAndMemory,diagnosticNetwork,diagnosticFonts,diagnosticPngExport,diagnosticZip,diagnosticServiceWorker,diagnosticOcr,diagnosticTmdb,diagnosticExternalImage,diagnosticRuntime];
  try{for(const check of checks){try{results.push(await check());}catch(error){results.push(diagnosticResult(check.name,check.name,'fail',error.message));}$('diagnosticsSummary').textContent=`Controllo ${results.length}/${checks.length}…`;}
    diagnosticsReport={createdAt:new Date().toISOString(),version:APP_VERSION,results:results.sort((a,b)=>diagnosticStatusRank(b.status)-diagnosticStatusRank(a.status)),runtimeIssues:deepClone(runtimeIssueLog)};renderDiagnosticsPanel();storageSet('cdb-last-diagnostic',JSON.stringify({createdAt:diagnosticsReport.createdAt,summary:diagnosticsReport.results.map(x=>({id:x.id,status:x.status}))}));const fail=results.filter(x=>x.status==='fail').length,warn=results.filter(x=>x.status==='warn').length;showToast(fail?`Diagnostica: ${fail} errori`:warn?`Diagnostica: ${warn} avvisi`:'Diagnostica completata');return diagnosticsReport;
  }finally{if(button)button.disabled=false;}
}
async function copyDiagnosticsReport(){const text=diagnosticReportText();try{if(navigator.clipboard?.writeText&&window.isSecureContext)await navigator.clipboard.writeText(text);else{const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();document.execCommand('copy');area.remove();}showToast('Rapporto copiato');}catch(error){showToast('Copia non disponibile');}}
function downloadDiagnosticsReport(){downloadBlob(new Blob([diagnosticReportText()],{type:'text/plain;charset=utf-8'}),`cdb-diagnostica-${new Date().toISOString().slice(0,10)}.txt`);showToast('Rapporto diagnostico salvato');}
async function refreshAppCache(){const button=$('refreshAppCacheBtn');if(button)button.disabled=true;try{let removed=0;if(typeof caches!=='undefined'){for(const key of await caches.keys())if(key.startsWith('cdb-studio-v')&&key!==`cdb-studio-v${APP_VERSION}`){await caches.delete(key);removed++;}}const reg=await navigator.serviceWorker?.getRegistration('./');if(reg)await reg.update();$('diagnosticsSummary').textContent=`Cache aggiornata${removed?` · rimosse ${removed} versioni precedenti`:''}. Riapri l’app per applicare tutto.`;$('diagnosticsSummary').className='inline-status success';showToast('Cache app aggiornata');}catch(error){$('diagnosticsSummary').textContent=`Aggiornamento cache non riuscito: ${error.message}`;$('diagnosticsSummary').className='inline-status error';}finally{if(button)button.disabled=false;}}
